%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%       Running this script will estimate the quality of a survey       %%
%             Please save and rename a copy of this template              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                       Make sure of the following                        %
%-------------------------------------------------------------------------%
%                  All functions are in the parent folder                 %
%                       Data can be in subfolders                         %
%                       See end of script for help                        %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                         Set input variables                           %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%% MODIFY
% Used by importSurvey (line 35)
filepath = 'F:\Acacia RA work\goodnessOfSurvey'; 
trackfile = 'Track Acacia adunca Bien Donne main site 20210119.gpx';
wpfile = 'Waypoint Acacia adunca Bien Donne 20210119.gpx';
tracklogs = 1:15; 
numberofwpts = 1:194; 
%%% DO NOT MODIFY
tk = 'track';
wpt = 'waypoint';

%%% MODIFY
% Used by plotSurvey (line 50)
bin_width = 1; % in meters
image = 'BDF.jpg';
world = 'BDF.jgw';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                          Import survey data                           %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

track = importSurvey(filepath, trackfile, tracklogs, tk);
waypoint = importSurvey(filepath, wpfile, numberofwpts, wpt);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                    Estimate survey site dimensions                    %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% surveyDim can take any number of imported tracks. Imported waypoints do
% not need to be passed through surveyDim.
[compiled_tracks, lat_dist, lon_dist] = surveyDim(track);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                           Plot survey data                            %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

[grddsrvy, bins, sdist] = plotSurvey(bin_width, lat_dist, lon_dist, ...
    compiled_tracks, waypoint, image, world);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                         Create summary table                          %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% all input variables are generated by the previous functions.
efficacy_table = surveyEfficacy(compiled_tracks, grddsrvy, bins, sdist);
disp(efficacy_table)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                           Function support                            %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Run the below lines individually, removing the % from before 'help'.
% Running these will give assistance on functionality.

% help importSurvey
% help surveyDim
% help plotSurvey
% help surveyEfficacy

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%